### ISSUE TITLE
Drop Ships

### ISSUE THREAD

**Issue by mhinterdorfer** [rstropek-teaching/real-time-game-quiz-4ahif-MHinterdorfer#1]
How is it possible to drop the ship-table into the game grid?

**Comment by rstropek** [comment]
Hi @MHinterdorfer 

Not 100% sure what you mean. Do you mean Drag & Drop? [jQuery offers helper functions for that](https://jqueryui.com/droppable/). Does this help?

If you like solving this puzzle, go on. It is an interesting and funny challenge. However, if you just want to practice for your exam, try to focus more on the Websockets- and/or Web API-part. You will definitely not have to implement something like Drag & Drop in your exam.

Greetings,
Rainer Stropek.

**Comment by mhinterdorfer** [comment]
Dear @rstropek 

Thanks for the fast reply! 
I will try to focus on these parts and implement the Drag&Drop later.
